services:
  - type: web
    name: natural-mystic-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node dist/main.js
    plan: free
    envVars:
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        sync: false
        value: ""
